<?php error_reporting(0); ?>
<!DOCTYPE html>
<html>
<head>
<title>Multilingua - registro pagos</title>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="view/default/css/style.css">
<link rel="stylesheet" type="text/css" href="view/default/css/editar_usuario.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<style>
html,body,h1,h2,h3,h4 {font-family:"Lato", sans-serif}
.mySlides {display:none}
.w3-tag, .fa {cursor:pointer}
.w3-tag {height:15px;width:15px;padding:0;margin-top:6px}
</style>

</head>
<body>
<div class="w3-row w3-container w3-dark-grey w3-padding:0">
    <div class="w3-section" style="width: 10%;	float: left;"><p><a href="https://multilingua.edu.co"><img src="view/default/images/Logo.png" width="150"  alt="logo multilingua"></a></p></div>
    <div class="w3-section w3-center" style="width: 89%; float: right;"><h1>Centro Digital de Registro</h1></div>
  </div>

<!--
	
	<div class="w3-container w3-dark-grey">
  <p><a href="https://multilingua.edu.co"><img src="view/default/images/Logo.png" width="200"  alt="logo multilingua"></a>Centro Digital de Registro</p>
</div>
	
 -->


