<?php 
require_once('view/default/vista-php/header.phtml');
		
?>



<!-- Content -->
<div class="w3-content" style="max-width:70%;margin-top:80px;margin-bottom:80px">

  <div class="w3-panel">
  
    <h2 class="titulos">Selecciona tu examen:</h2>
  </div>

  
  <!-- Grid -->
  <div class="w3-row w3-container">
    <div class="w3-center w3-padding-16">
    <div class="w3-section" style="width: 30%;	float: left;"> <a href="vista.php?var=registro&amp;exam=ket"><img src="view/default/img/vista/exam_ket.png" alt="ket" class="w3-hover-opacity w3-image"></a>
    </div>
    <div class="w3-section" style="width: 30%;	float: left;"> <a href="vista.php?var=registro&amp;exam=pet"><img src="view/default/img/vista/exam_pet.png" alt="pet" class="w3-hover-opacity w3-image"></a>
    </div>
    <div class="w3-section" style="width: 30%;	float: left;"> <a href="vista.php?var=registro&amp;exam=fce"><img src="view/default/img/vista/exam_fce.png" alt="exam_fce" class="w3-hover-opacity w3-image"></a>
    </div>
    <div class="w3-section" style="width: 30%;	float: left;"> <a href="vista.php?var=registro&amp;exam=cae"><img src="view/default/img/vista/exam_cae.png" alt="cae" class="w3-hover-opacity w3-image"></a>
    </div>
     <div class="w3-section" style="width: 30%;	float: left;"> <a href="vista.php?var=registro&amp;exam=tkt"><img src="view/default/img/vista/exam_tkt.png" alt="tkt" class="w3-hover-opacity w3-image"></a>
     </div>
     <div class="w3-section" style="width: 30%;	float: left;"> <a href="vista.php?var=registro&amp;exam=cept"><img src="view/default/img/vista/exam_cept.png" alt="cept" class="w3-hover-opacity w3-image"></a>
     </div>
     <div class="w3-section" style="width: 30%;	float: left;"> <a href="vista.php?var=registro&amp;exam=linguaskill"><img src="view/default/img/vista/exam_linguaskill.png" alt="linguaskill" class="w3-hover-opacity w3-image"></a>
     </div>
     <div class="w3-section" style="width: 30%;	float: left;"> <a href="vista.php?var=registro&amp;exam=met"><img src="view/default/img/vista/exam_met.png" alt="met" class="w3-hover-opacity w3-image"></a>
     </div>
     <div class="w3-section" style="width: 30%;	float: left;"> <a href="vista.php?var=registro&amp;exam=toeic"><img src="view/default/img/vista/exam_toeic.png" alt="toeic" class="w3-hover-opacity w3-image"></a>
     </div>
   
   
   
   
    
    <div class="w3-panel">
    <hr>
    </div>

   

    </div>
    </div>
 
<?php require_once('footer.phtml');?>
