<?php 
require_once('view/default/vista-php/header.phtml');
		
?>
<style type="text/css" media="screen">
.input-hidden {
  position: absolute;
  left: -9999px;
}

input[type=radio]:checked + label>img {
 
  box-shadow: 0 0 3px 3px #d6d6d6;
    border-bottom: solid 2px #55afa1;
}

/* Stuff after this is only to make things more pretty */
input[type=radio] + label>img {
	border-radius: 10%;
    padding: 1%;
margin: 0.2em;
    transition: 500ms all;
    background-color: #fff;
    max-width: 100px;
    border: solid 1px #e0e0e0;
}
.bancos
{
width: 200px;
}
</style>


<!-- Content -->
<div class="w3-content" style="max-width:70%;margin-top:80px;margin-bottom:80px">

  <div class="w3-panel">
    <h4 class="titulos">Datos del estudiante o candidato que tomar&aacute; el servicio<hr></h4>
  </div>

  
  <!-- Grid -->
  <div class="w3-row w3-container">
    <div class="w3-center w3-padding-10">
    
    
    <form method="get" class="w3-container" action="#">
    <div class="w3-section" style="width: 30%;	float: left;">
      <img src="view/img/vista/exam_ket.png" alt="ket" class="w3-hover-opacity">
    </div>
    <div class="w3-section" style="width: 30%;	float: right;">
     <img src="view/img/vista/exam_pet.png" alt="pet" class="w3-hover-opacity">
    </div>
    <div class="w3-section" style="width: 30%;	float: right;">
     <img src="view/img/vista/exam_fce.png" alt="exam_fce" class="w3-hover-opacity">
    </div>
    <div class="w3-section" style="width: 49%;	float: right;">
      <img src="image.jpg" alt="Einstein" class="w3-hover-opacity">
    </div>
    <div class="w3-section" style="width: 49%;	float: left;">
      <label>Direcci&oacute;n</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" type="text" name="DIRECCION" required>
    </div>
     <div class="w3-section" style="width: 49%;	float: right;">
      <label>N&uacute;mero de celular</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" type="text" name="CELULAR" required>
    </div>
    
    <div class="w3-panel">
    <hr><h4 class="titulos">Recuerde que los datos en este formulario, son de la persona que va a tomar el servicio (Examen, Curso, etc).</h4><hr>


<button onclick="myFunction('Demo1')" class="w3-btn w3-block w3-teal w3-left-align"> &#9660; Seleccione metodo de pago dando click sobre la imagen - Aqu&iacute; *</button>
<div id="Demo1" class="w3-container w3-hide">
<!-- metodos de pago -->
<div class="w3-container">
<div class="w3-section" style="width: 20%; float: left;">
      <label>Tarjeta de Cr&eacute;dito.</label>
      
    </div>
     <div class="w3-section" style="width: 79%;	float: right;">
      <input 
  type="radio" name="metodo_pago" 
  id="visa" class="input-hidden" required value="visa" >
<label for="visa">
  <img 
    src="../../view/default/images/VISA.png" 
    alt="VISA" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="master" class="input-hidden" required value="mastercard">
<label for="master">
  <img 
    src="../../view/default/images/MASTER.png" 
    alt="MASTER" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="amex" class="input-hidden" required value="amex">
<label for="amex">
  <img 
    src="../../view/default/images/AMEX.png" 
    alt="AMEX" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="diners" class="input-hidden" required value="diners">
<label for="diners">
  <img 
    src="../../view/default/images/DINERS.png" 
    alt="DINERS" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="codensa" class="input-hidden" required value="codensa">
<label for="codensa">
  <img 
    src="../../view/default/images/CODENSA.png" 
    alt="CODENSA" />
</label>

    </div>
</div>
<hr>
<div class="w3-container">
<div class="w3-section" style="width: 20%; float: left;">
      <label>D&eacute;bito, transferencia bancaria.</label>
      
    </div>
     <div class="w3-section" style="width: 79%;	float: right;">
      <input 
  type="radio" name="metodo_pago" 
  id="pse" class="input-hidden" required value="pse">
<label for="pse">
  <img 
    src="../../view/default/images/PSE.png" 
    alt="PSE" />
</label>


    </div>
    </div>
    <hr>
    <div class="w3-container">
   
    <div class="w3-section" style="width: 20%; float: left;">
      <label>Efectivo.</label>
      
    </div>
     <div class="w3-section" style="width: 79%;	float: right;">
      <input 
  type="radio" name="metodo_pago" 
  id="baloto" class="input-hidden" required value="baloto">
<label for="baloto">
  <img 
    src="../../view/default/images/baloto.png" 
    alt="BALOTO" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="pagatodo" class="input-hidden" required value="pagatodo">
<label for="pagatodo">
  <img 
    src="../../view/default/images/pagatodo.png" 
    alt="PAGA TODO" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="apuestascucuta" class="input-hidden" required value="apuestascucuta">
<label for="apuestascucuta">
  <img 
    src="../../view/default/images/apuestascucuta.png" 
    alt="apuestascucuta" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="gana" class="input-hidden" required value="gana">
<label for="gana">
  <img 
    src="../../view/default/images/gana.png" 
    alt="gana" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="ganagana" class="input-hidden" required value="ganagana">
<label for="ganagana">
  <img 
    src="../../view/default/images/ganagana.png" 
    alt="ganagana" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="suchance" class="input-hidden" required value="suchance">
<label for="suchance">
  <img 
    src="../../view/default/images/suchance.png" 
    alt="suchance" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="acertemos" class="input-hidden" required value="acertemos">
<label for="acertemos">
  <img 
    src="../../view/default/images/acertemos.png" 
    alt="acertemos" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="perla" class="input-hidden" required value="perla">
<label for="perla">
  <img 
    src="../../view/default/images/perla.png" 
    alt="perla" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="apuestasunidas" class="input-hidden" required value="apuestasunidas">
<label for="apuestasunidas">
  <img 
    src="../../view/default/images/apuestasunidas.png" 
    alt="apuestasunidas" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="jer" class="input-hidden" required value="jer">
<label for="jer">
  <img 
    src="../../view/default/images/jer.png" 
    alt="jer" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="efecty" class="input-hidden" required value="efecty">
<label for="efecty">
  <img 
    src="../../view/default/images/efecty.png" 
    alt="efecty" />
</label>


    </div>
    </div>

 <hr>
    <div class="w3-container">
   
    <div class="w3-section" style="width: 20%; float: left;">
      <label>Consignaci&oacute;n bancaria.</label>
      
    </div>
     <div class="w3-section" style="width: 79%;	float: right;">
      <input 
  type="radio" name="metodo_pago" 
  id="bogota" class="input-hidden" required value="bogota">
<label for="bogota">
  <img class="bancos"
    src="../../view/default/images/BOGOTA.png" 
    alt="bogota" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="bancolombia" class="input-hidden" required value="bancolombia">
<label for="bancolombia">
  <img class="bancos"
    src="../../view/default/images/BANCOLOMBIA.png" 
    alt="bancolombia" />
</label>
<input 
  type="radio" name="metodo_pago" 
  id="davivienda" class="input-hidden" required value="davivienda">
<label for="davivienda">
  <img class="bancos"
    src="../../view/default/images/DAVIVIENDA.png" 
    alt="davivienda" />
</label>



    </div>
    </div>
    <hr>
     <input class="w3-input" type="radio"  name="terminos" required><label> Acepto que en caso de solicitar un reembolso se retendr&aacute; el 7% del valor total de la compra*</label>
    </div>
<!-- metodos de pago -->
    </div>
     
   <!-- variables para payu -->

<input type="hidden" name="buyerEmail" id="emailAddress" value="correo@correo.com">
<input type="hidden" name="buyerFullName" valid-pattern="VALID_BUYER_NAME" id="fullName" value="nombre completo">
<!-- variables para payu -->
    <input type="hidden" name="form" value="datos">
    <input type="hidden" name="product" value="<?php echo $_REQUEST['product']; ?>">
    <button type="submit" class="w3-button w3-block w3-black" style="width:30%;">Continuar con el pago</button>
  </form>

    
   
    </div>
  
</div>
<script>
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>
<?php require_once('footer.phtml');?>
