<?php 
require_once('view/default/vista-php/header.phtml');
		
?>
<style type="text/css" media="screen">
.input-hidden {
  position: absolute;
  left: -9999px;
}


</style>


<!-- Content -->
<div class="w3-content" style="max-width:70%;margin-top:80px;margin-bottom:80px">

  <div class="w3-panel">
  <img src="view/default/img/vista/exam_<?php echo $_REQUEST['exam'] ?>.png" width="300" height="91" alt="<?php echo $_REQUEST['exam'] ?>" />
<h4 class="titulos">Datos del estudiante o candidato que tomar&aacute; el servicio<hr></h4>
  </div>

  
  <!-- Grid -->
  <div class="w3-row w3-container">
    <div class="w3-center w3-padding-10">
    
    
    <form method="post" class="w3-container" action="#" enctype="multipart/form-data">
    <div class="w3-section" style="width: 49%;	float: left;">
      <label>Nombres</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" name="NOMBRE" required type="text">
    </div>
    <div class="w3-section" style="width: 49%;	float: right;">
      <label>Apellidos</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" name="APELLIDOS" required type="text">
    </div>
    <div class="w3-section" style="width: 49%;	float: left;">
      <label>Cedula</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" name="CEDULA" required type="text">
    </div>
    <div class="w3-section" style="width: 49%;	float: right;">
      <label>Correo</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" name="MAIL" required type="text">
    </div>
    <div class="w3-section" style="width: 49%;	float: left;">
      <label>Direcci&oacute;n</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" type="text" name="DIRECCION" required>
    </div>
     <div class="w3-section" style="width: 49%;	float: right;">
      <label>N&uacute;mero de celular</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" type="text" name="CELULAR" required>
    </div>
     <div class="w3-section" style="width: 49%;	float: left;">
      <label>Scanner / Fotocopia Documento Identidad<br />"jpg, png, jpeg"</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" type="file" name="documento_identidad" required placeholder="jpg, png, jpeg">
    </div>
     <div class="w3-section" style="width: 49%;	float: right;">
      <label>Carta de compromiso y Registration Form<br />"pdf"</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" type="file" name="compromiso_registration" required placeholder="pdf">
    </div>
     <div class="w3-section" style="width: 49%;	float: left;">
      <label>Comprobante de Transacci&oacute;n<br />"jpg, png, jpeg"</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" type="file" name="compromiso_registration" required placeholder="jpg, png, jpeg">
    </div>
    
    <div class="w3-panel">
    <hr>

    <input type="hidden" name="exam" value="<?php echo $_REQUEST['exam']; ?>">
    <input type="hidden" name="MAX_FILE_SIZE" value="3000" />
    <button type="submit" class="w3-button w3-block w3-teal" style="width:30%; margin-left: 35%;">Enviar inscripción</button>
     </div>
      <hr>
  </form>

    
   
    </div>
  
</div>

<?php require_once('footer.phtml');?>
