<?php require_once('header.phtml');?>

<!-- Content -->
<div class="w3-content" style="max-width:70%;margin-top:80px;margin-bottom:80px">

  <div class="w3-panel">
    <h4><b><?php echo $metodo.' '. $controlador; ?></b><hr></h4>
  </div>

  
  <!-- Grid -->
  <div class="w3-row w3-container">
    <div class="w3-center w3-padding-10">
    
    
    <form method="get" class="w3-container" action="#">
    <div class="w3-section">
      <label>Nombre del Calendario</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" name="NOMBRE" required="" type="text" maxlength="40" value="<?php echo $_REQUEST['nombre']; ?>">
    </div>
    <div class="w3-section">
      <label>Propietario</label>
      <select name="PROPIETARIO" class="w3-input w3-border w3-hover-border-black" style="width:100%;" value="<?php echo $_REQUEST['mail_creador']; ?>">
		  <?php
		  echo '<option value="'.$_REQUEST['mail_creador'].'" selected>'.$_REQUEST['mail_creador'].'</option>';
		 
			while ($indice = mysqli_fetch_array($propietarios, MYSQL_ASSOC)) {
			
			foreach ($indice as $ind => $col_value) {
			echo '<option value="'.$col_value.'">'.$col_value.'</option>';
			}
			
			}
			mysqli_free_result($propietarios);
			unset($propietarios);
		  ?>
		</select>
	
    </div>
   
     <div class="w3-section" style="width: 33%;	float: left;">
     <label>Activo</label>
      <select name="ACTIVO" class="w3-input w3-border w3-hover-border-black" style="width:100%;">
		  <option value="<?php echo $_REQUEST['activo']; ?>" selected><?php echo $_REQUEST['activo']; ?></option>
		  <option value="inactivo">Desactivar</option>
		  <option value="activo">Activar</option>
		</select>
    </div>
   <div class="w3-section" style="width: 33%;	float: right;">
     <label>Tipo</label>
      <select name="GRUPO" class="w3-input w3-border w3-hover-border-black" style="width:100%;">
		  <option value="<?php echo $_REQUEST['grupo']; ?>" selected><?php echo $_REQUEST['grupo']; ?></option>
		  <option value="general">Ninguno</option>
		  <option value="ielts">Ielts</option>
		</select>
    </div>
    </div><input type="hidden" name="guardar_editar" value="1">
    <input type="hidden" name="c" value="<?php echo $_REQUEST['c']; ?>">
    <input type="hidden" name="m" value="<?php echo $_REQUEST['m']; ?>">
    <input type="hidden" name="ID" value="<?php echo $_REQUEST['ID']; ?>">
    
    <div class="w3-section"><button type="submit" class="w3-button w3-block w3-black" style="width:30%;">Guardar</button></div>
  </form>

    
   
    </div>
  
</div>

<?php require_once('footer.phtml');?>
