<?php require_once('header.phtml');?>


<!-- Content -->
<div class="w3-content" style="max-width:70%;margin-top:80px;margin-bottom:80px">

  <div class="w3-panel">
    <h4><b><?php echo $metodo.' '. $controlador; ?></b><hr></h4>
  </div>

  
  <!-- Grid -->
  <div class="w3-row w3-container">
    <div class="w3-center w3-padding-10">
    <div class="w3-section" style="border: 1px solid #D8D8D8;  border-radius: 10px;  padding: 1em; box-shadow: -webkit-box-shadow: -2px 4px 13px -8px rgba(0,0,0,0.75);
-moz-box-shadow: -2px 4px 13px -8px rgba(0,0,0,0.75);
box-shadow: -2px 4px 13px -8px rgba(0,0,0,0.75);">
    
    <form method="get" class="w3-container" action="#">
    
    <div class="w3-section">
      <label>Nombre del Calendario</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" name="NOMBRE" required="" type="text" maxlength="40" value="<?php echo $_REQUEST['nombre']; ?>">
    </div>
   <div class="w3-section" style="width: 40%; float: left;">
   
<!-- FLOTANTE -->

<!-- FLOTANTE -->
   
   
   </div>
   
     <div class="w3-section" style="width: 40%;	float: right;">
     <label>Activo</label>
      <select name="ESTADO" class="w3-input w3-border w3-hover-border-black" style="width:100%;">
		  <option value="<?php echo $_REQUEST['estado']; ?>" selected><?php echo $_REQUEST['estado']; ?></option>
		  <option value="inactivo">Desactivar</option>
		  <option value="activo">Activar</option>
		</select>
    </div>
   </div>
    
    <input type="hidden" name="EDITOR" value="<?php echo $_REQUEST['editor']; ?>">
    <input type="hidden" name="guardar_editar" value="1">
    <input type="hidden" name="c" value="<?php echo $_REQUEST['c']; ?>">
    <input type="hidden" name="m" value="<?php echo $_REQUEST['m']; ?>">
    <input type="hidden" name="ID" value="<?php echo $_REQUEST['ID']; ?>">
    
    <div class="w3-section"><button type="submit" class="w3-button w3-block w3-black" style="width:20%;">Guardar</button></div>
  </form>


    
   </div>
    </div>
  <button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Iniciar sesión</button>
</div>

<?php require_once('footer.phtml');?>
