<?php require_once('header.phtml');?>

<!-- Content -->
<div class="w3-content" style="max-width:90%;margin-top:80px;margin-bottom:80px">

  <div class="w3-panel">
    <h4><b><?php echo ucwords($metodo).' '. ucwords($controlador); ?></b><hr></h4>
  </div>

  
  <!-- Grid -->
  <div class="w3-row w3-container">
    <div class="w3-center w3-padding-10 w3-width-80%">
    <div class="listar w3-hover-shadow">
    

      <?php 
	  /*
      //ENLACES TABLA
while ($indice = mysql_fetch_array($resultado, MYSQL_ASSOC)) {
		
		foreach ($indice as $ind => $col_value) {
        echo '&ltth&gt &lta href="index.php?c=productos&orden='.$ind.'"&gt &lt/a&gt &lt/th&gt &ltbr&gt<br>';
		}
	}
//ENLACES TABLA   
   */
   
   echo '<table>
   <thead>
              <tr>
                <th> <a href="index.php?c=productos&orden=ID"> No.</a> </th> 
				<th> <a href="index.php?c=productos&orden=IMAGEN"> Imagen</a> </th> 
				<th> <a href="index.php?c=productos&orden=TITULO"> T&iacute;tulo</a> </th> 
				<th> <a href="index.php?c=productos&orden=DESCRIPCION"> Descripci&oacute;n</a> </th> 
				<th> <a href="index.php?c=productos&orden=PRECIO"> Precio</a> </th> 
				<th> <a href="index.php?c=productos&orden=URL"> URL</a> </th>
				<th> <a href="index.php?c=productos&orden=NOMBRE_PASARELA"> Slug</a> </th> 
				<th> <a href="index.php?c=productos&orden=ACTIVO"> Activo</a> </th> 
				<th> <a href="index.php?c=productos&orden=GRUPO"> Grupo</a> </th>
				<th> <a href="index.php?c=productos&orden=FECHA_CREADO"> Fecha</a> </th>
              </tr>
            </thead>
            <tbody><!--!important -->';
		while ($indice = mysqli_fetch_array($resultado, MYSQLI_ASSOC)) {
		echo "<tr>";
		foreach ($indice as $ind => $col_value) {
			if($ind == "URL")
			{
				echo '<td data-label="'.$ind.'"><a href="'.$col_value.'" target="_blank">'.$col_value.'</a></td>';
			}
			else
			{
				echo '<td data-label="'.$ind.'">'.$col_value.'</td>';
			}
        
		}
		echo "</tr>";
		}
		echo "<tbody></table>";
		mysqli_free_result($resultado);
		unset($resultado);
    ?>
    </div>
    </div>
  
</div>

<?php require_once('footer.phtml');?>
