<?php require_once('header.phtml');?>

<!-- Content -->
<div class="w3-content" style="max-width:70%;margin-top:80px;margin-bottom:80px">

  <div class="w3-panel">
    <h4><b><?php echo $metodo.' '. $controlador; ?></b><hr></h4>
  </div>

  
  <!-- Grid -->
  <div class="w3-row w3-container">
    <div class="w3-center w3-padding-10">
    
    
    <form method="get" class="w3-container" action="#">
    <div class="w3-section">
      <label>Seleccione la fecha para crear el recordatorio</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" name="FECHA_RECORDAR_EVENTO" required="" type="date" value="<?php echo $_REQUEST['FECHA_RECORDAR_EVENTO'];?>">
    </div>
    </div><input type="hidden" name="guardar" value="1">
    <input type="hidden" name="ACTIVO_EVENTO" value="activo">
    <input type="hidden" name="editar-recordatorio-form" value="1">
    
    <input type="hidden" name="ID-RECORDATORIO" value="<?php echo $_REQUEST['ID-RECORDATORIO']; ?>">
    <input type="hidden" name="ID-EVENTO" value="<?php echo $_REQUEST['ID-EVENTO']; ?>">
    <input type="hidden" name="c" value="<?php echo $_REQUEST['c']; ?>">
    <input type="hidden" name="m" value="<?php echo $_REQUEST['m']; ?>">
    
    <div class="w3-section"><button type="submit" class="w3-button w3-block w3-black" style="width:30%;">Guardar</button></div>
  </form>

    
   
    </div>
  
</div>

<?php require_once('footer.phtml');?>
