<?php error_reporting(0); ?>
<!DOCTYPE html>
<html>
<head>
<title>Multilingua <?php echo $metodo.'-'.$controlador;?></title>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="view/default/css/style.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4 {font-family:"Lato", sans-serif}
.mySlides {display:none}
.w3-tag, .fa {cursor:pointer}
.w3-tag {height:15px;width:15px;padding:0;margin-top:6px}
body
{
	background-image: url("<?php echo 'view/default/images/session/'.rand(1,10).'.jpg';?>");
	background-size: cover; 
	background-repeat: no-repeat;
}
</style>
<script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
	
	<!-- Links (sit on top) -->

<div class="w3-top">
 

</div>
<!-- Content -->
<div class="w3-content" style="max-width:70%;margin-top:80px;margin-bottom:80px">

  <div class="w3-panel">
    <h4><b><?php echo "Inicie sesión"; ?></b></h4>
  </div>

  
  <!-- Grid -->
  <div class="w3-row w3-container w3-half" style="border: 1px solid #d4d4d4; border-radius: 10px;">
    <div class="w3-center w3-padding-10">
    
    
    <form method="post" name="form1" id="form1" class="w3-container" action="#">
    <div class="w3-section">
      <label>Usuario</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" name="usuario" required="yes" type="text">
    </div>
    <div class="w3-section">
      <label>Contrase&ntilde;a</label>
      <input class="w3-input w3-border w3-hover-border-black" style="width:100%;" name="contrasena" required="yes" type="password">
    </div>
    <input type="hidden" name="m" value="autenticar">
    <div class="g-recaptcha" data-sitekey="6Ldk-DAUAAAAAHEoudoLrDBpMURokFPMxUkQq63v"></div><hr>
    <button type="submit" class="w3-button w3-block w3-black" style="width:30%;">Ingresar</button>
  </form>
  <div class="w3-section" style="border: 1px solid #f3a5a5; border-radius: 10px; opacity: 0.7; background-color: #fff">
	  <h4><?php echo $titulo; ?></h4>
	  <p><?php echo $mensaje; ?></p>
	  <p><a href="index.php?c=session&m=recuperar">Olvide mi contraseña</a></p>
	  </div>
	  
    </div>
  </div>
</div>

<!-- Footer -->

<footer class="w3-container w3-padding-32 w3-center">
  <h4></h4>
  
  
 </footer>



</body>
</html>
