<?php require_once('header.phtml');?>

<!-- Content -->
<div class="w3-content" style="max-width:90%;margin-top:80px;margin-bottom:80px">

  <div class="w3-panel">
    <h4><b><?php echo $metodo.' '. $controlador; ?></b><hr></h4>
  </div>

  
  <!-- Grid -->
  <div class="w3-row w3-container">
    <div class="w3-center w3-padding-10 w3-width-80%">
    <div class="listar w3-hover-shadow">
    

      <?php 
   
   echo '<table>
   <thead>
              <tr>
                <th> <a href="index.php?c=usuarios&orden=ID"> No.</a> </th> 
                <th> <a href="index.php?c=usuarios&orden=MENU"> Menu</a> </th> 
				<th> <a href="index.php?c=usuarios&orden=PERMISOS"> Permisos</a> </th> 
				<th> <a href="index.php?c=usuarios&orden=NOMBRE"> Nombre</a> </th> 
				<th> <a href="index.php?c=usuarios&orden=APELLIDOS"> Apellidos</a> </th> 
				<th> <a href="index.php?c=usuarios&orden=CEDULA"> Cedula</a> </th> 
				<th> <a href="index.php?c=usuarios&orden=MAIL"> Correo</a> </th>
				<th> <a href="index.php?c=usuarios&orden=CONTRASENA"> Contrase&ntilde;a</a> </th> 
				<th> <a href="index.php?c=usuarios&orden=ESTADO"> Estado</a> </th> 
				<th> <a href="index.php?c=usuarios&orden=FECHA_CREADO"> Fecha</a> </th>
              </tr>
            </thead>
            <tbody><!--!important -->';
		while ($indice = mysqli_fetch_array($resultado, MYSQL_ASSOC)) {
		echo "<tr>";
		foreach ($indice as $ind => $col_value) {
        echo '<td data-label="'.$ind.'">'.$col_value.'</td>';
		}
		echo "</tr>";
		}
		echo "<tbody></table>";
    ?>
    </div>
    </div>
  
</div>

<?php require_once('footer.phtml');?>
